apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: monitor-access
rules:
  - apiGroups: [""]
    resources:
      - events
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: monitor-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-access
subjects:
- kind: ServiceAccount
  name: pod-monitor
  namespace: monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pi-monitor
  namespace: monitor
  labels:
    app: k8s-light-monitor
spec:
  selector:
    matchLabels:
      app: k8s-light-monitor
  template:
    metadata:
      labels:
        app: k8s-light-monitor
    spec:
      serviceAccountName: pod-monitor
      containers:
      - name: light-monitor
        image: mikesir87/k8s-blinkstick-node-monitor
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        env:
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: dev
        hostPath:
          path: /dev